server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://47.98.52.95:6789/movietime?characterEncoding=UTF-8
    username: root
    password: klav
  jpa:
    show-sql: true